name: Deploy AWS Academy - EKS
on:
  push:
    branches:
      - main
env:
  AWS_REGION: "us-east-1"
  EKS_CLUSTER_NAME: "EKS-FIAP"
jobs:
  deploy:
    name: Deploy AWS Academy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Kube Apply
        run: |
          kubectl apply -f k8s/eks-deployment.yaml
          kubectl apply -f k8s/eks-svc.yaml